import type { Company } from '@shared/types';

export const companies: Company[] = [
	{
		id: 1,
		name: 'TechVision Global',
		countryCode: 'US',
		address: '123 Innovation Drive, San Francisco, CA 94105',
		website: 'techvision.com',
		stockCode: 'NASDAQ:TCVG',
	},
	{
		id: 2,
		name: 'NexGen Solutions',
		countryCode: 'US',
		address: '45 Oxford Street, London, W1D 1BW',
		website: 'nexgensolutions.co.uk',
		stockCode: 'LSE:NGS',
	},
	{
		id: 3,
		name: 'Quantum Industries',
		countryCode: 'DE',
		address: 'Hauptstrasse 56, Berlin, 10115',
		website: 'quantum-industries.de',
		stockCode: 'FWB:QIN',
	},
	{
		id: 4,
		name: 'Sunrise Technologies',
		countryCode: 'JP',
		address: '2-1-1 Marunouchi, Chiyoda-ku, Tokyo, 100-0005',
		website: 'sunrisetech.jp',
		stockCode: 'TSE:SNRT',
	},
	{
		id: 5,
		name: 'Alpine Software Group',
		countryCode: 'CH',
		address: 'Bahnhofstrasse 21, Zürich, 8001',
		website: 'alpinesoftware.ch',
		stockCode: 'SIX:ASG',
	},
	{
		id: 6,
		name: 'Oceanic Dynamics',
		countryCode: 'US',
		address: '101 Harbour Street, Miami, NSW 2000',
		website: 'oceanicdynamics.com',
		stockCode: 'ASX:ODY',
	},
	{
		id: 7,
		name: 'Nordic Innovations',
		countryCode: 'SE',
		address: 'Sveavägen 10, Stockholm, 111 57',
		website: 'nordicinnovations.se',
		stockCode: 'OMX:NINN',
	},
	{
		id: 8,
		name: 'Maple Systems',
		countryCode: 'CA',
		address: '250 University Avenue, Toronto, ON M5H 3E5',
		website: 'maplesystems.ca',
		stockCode: 'TSX:MSYS',
	},
	{
		id: 9,
		name: 'Emerald Enterprises',
		countryCode: 'IE',
		address: '25 Grafton Street, Dublin, D02 HF62',
		website: 'emeraldenterprises.ie',
		stockCode: 'EURONEXT:EME',
	},
	{
		id: 10,
		name: 'Solar Dynamics',
		countryCode: 'ES',
		address: 'Gran Vía 42, Madrid, 28013',
		website: 'solardynamics.es',
		stockCode: 'BME:SLDN',
	},
	{
		id: 11,
		name: 'Digital Frontier',
		countryCode: 'SG',
		address: '1 Raffles Place, Singapore, 048616',
		website: 'digitalfrontier.sg',
		stockCode: 'SGX:DFSG',
	},
	{
		id: 12,
		name: 'Azure Networks',
		countryCode: 'FR',
		address: '15 Avenue des Champs-Élysées, Paris, 75008',
		website: 'azurenetworks.fr',
		stockCode: 'EPA:AZNW',
	},
	{
		id: 13,
		name: 'Pinnacle Semiconductors',
		countryCode: 'KR',
		address: '123 Teheran-ro, Gangnam-gu, Seoul, 06234',
		website: 'pinnaclesemi.kr',
		stockCode: 'KRX:PSEM',
	},
	{
		id: 14,
		name: 'Meridian Robotics',
		countryCode: 'IL',
		address: '26 Rothschild Boulevard, Tel Aviv, 6688101',
		website: 'meridianrobotics.co.il',
		stockCode: 'TASE:MDRB',
	},
	{
		id: 15,
		name: 'Verdant Biotechnology',
		countryCode: 'BR',
		address: 'Avenida Paulista 1000, São Paulo, 01310-100',
		website: 'verdantbio.com.br',
		stockCode: 'B3:VBIO',
	},
	{
		id: 16,
		name: 'Nimbus Computing',
		countryCode: 'NL',
		address: 'Herengracht 595, Amsterdam, 1017 CE',
		website: 'nimbuscomputing.nl',
		stockCode: 'AMS:NMBC',
	},
	{
		id: 17,
		name: 'Sapphire Telecom',
		countryCode: 'IN',
		address: 'DLF Cyber City, Gurgaon, Haryana 122002',
		website: 'sapphiretelecom.in',
		stockCode: 'BSE:SPTR',
	},
	{
		id: 18,
		name: 'Avalon Microelectronics',
		countryCode: 'TW',
		address: 'No. 101, Section 2, Hsinyi Road, Taipei, 110',
		website: 'avalonmicro.tw',
		stockCode: 'TWSE:AVLN',
	},
	{
		id: 19,
		name: 'Helios Energy Solutions',
		countryCode: 'AE',
		address: 'Sheikh Zayed Road, Dubai, P.O. Box 123456',
		website: 'heliosenergy.ae',
		stockCode: 'DFM:HELS',
	},
	{
		id: 20,
		name: 'Polar Cloud Services',
		countryCode: 'FI',
		address: 'Mannerheimintie 15, Helsinki, 00100',
		website: 'polarcloud.fi',
		stockCode: 'HEL:POLS',
	},
	{
		id: 21,
		name: 'Atlas Security Systems',
		countryCode: 'ZA',
		address: '100 Main Street, Cape Town, 8001',
		website: 'atlassecurity.co.za',
		stockCode: 'JSE:ATLS',
	},
	{
		id: 22,
		name: 'Vortex Data Analytics',
		countryCode: 'IT',
		address: 'Via Veneto 33, Rome, 00187',
		website: 'vortexdata.it',
		stockCode: 'BIT:VRTX',
	},
	{
		id: 23,
		name: 'Horizon Aerospace',
		countryCode: 'FR',
		address: '5 Rue de la Paix, Toulouse, 31000',
		website: 'horizonaero.fr',
		stockCode: 'EPA:HZNA',
	},
	{
		id: 24,
		name: 'Cascade Pharmaceuticals',
		countryCode: 'CH',
		address: 'Elisabethenstrasse 23, Basel, 4051',
		website: 'cascadepharma.ch',
		stockCode: 'SIX:CSPH',
	},
	{
		id: 25,
		name: 'Equinox Financial Services',
		countryCode: 'HK',
		address: '88 Queensway, Admiralty, Hong Kong',
		website: 'equinoxfinancial.hk',
		stockCode: 'HKEX:EQFN',
	},
	{
		id: 26,
		name: 'Phoenix Automation',
		countryCode: 'SE',
		address: 'Kungsgatan 32, Stockholm, 111 35',
		website: 'phoenixautomation.se',
		stockCode: 'OMX:PHXA',
	},
	{
		id: 27,
		name: 'Oasis Media Group',
		countryCode: 'NO',
		address: 'Karl Johans gate 33, Oslo, 0162',
		website: 'oasismedia.no',
		stockCode: 'OSE:OASM',
	},
	{
		id: 28,
		name: 'Borealis Software',
		countryCode: 'DK',
		address: 'Rådhuspladsen 16, Copenhagen, 1550',
		website: 'borealis-software.dk',
		stockCode: 'CPH:BORL',
	},
	{
		id: 29,
		name: 'Quantum Materials',
		countryCode: 'CN',
		address: '1088 Century Avenue, Pudong, Shanghai, 200120',
		website: 'quantummaterials.cn',
		stockCode: 'SSE:QTMT',
	},
	{
		id: 30,
		name: 'Sigma Healthcare Technologies',
		countryCode: 'BE',
		address: 'Avenue Louise 250, Brussels, 1050',
		website: 'sigmahealthtech.be',
		stockCode: 'EBR:SGHT',
	},
];

export default companies;
